[package]
name = "phrep"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
tree-sitter = "0.20"
walkdir = "2.4"
anyhow = "1.0"
regex = "1.11.1"
tree-sitter-php = "0.23.11"
colored = "3.0.0"
dirs = "6.0.0"
